name: cache-action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/example   # pretend this is a folder with deps
          key: cache-a7d222d

      - name: prime-cache-a7d222d
        run: echo "Cache result = ${{ steps.cache.outputs.cache-hit }}"
